//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConneixTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_Id { get; set; }
        public string Emp_FirstName { get; set; }
        public string Emp_LastName { get; set; }
        public string Emp_Email { get; set; }
        public Nullable<decimal> Emp_Salary { get; set; }
        public string Emp_Designation { get; set; }
        public Nullable<System.DateTime> Emp_DOB { get; set; }
        public string Emp_Address { get; set; }
        public string Gender { get; set; }
    }
}
